name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: fmt
        run: cargo fmt -- --check
      # - name: Audit
      #   run: cargo audit
      - name: clippy
        run: cargo clippy
# name: Security audit
# on:
#   schedule:
#     - cron: '0 0 * * *'
#   push:
#     paths:
#       - '**/Cargo.toml'
#       - '**/Cargo.lock'
# jobs:
#   security_audit:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: taiki-e/install-action@cargo-deny
#       - name: Scan for vulnerabilities
#         run: cargo deny check advisories
